### ISSUE TITLE
HastiBus should contain a Default Slave

### ISSUE THREAD

**Issue by pbing** [ucb-bar/junctions#10]
See "AMBA® 3 AHB-Lite Protocol v1.0" section 4.1.1:

If a system design does not contain a completely filled memory map then you must implement an additional default slave to provide a response when any of the nonexistent address locations are accessed.
If a NONSEQUENTIAL or SEQUENTIAL transfer is attempted to a nonexistent address location then the default slave provides an ERROR response.
IDLE or BUSY transfers to nonexistent locations result in a zero wait state OKAY response.

**Comment by aswaterman** [comment]
We'll take this under advisement, but these bus interfaces are all subsets
of the corresponding AMBA ones and so will in general not offer all
features.

**Comment by terpstra** [comment]
There is now a default slave, however, at the moment it responds with success. Once TileLink supports bus errors, we will report errors from the HastiXbar as well. Until then, it would cause assertion failures.
