### ISSUE TITLE
Hasti xbar looses transfers 

### ISSUE THREAD

**Issue by boehmerst** [ucb-bar/junctions#2]
Hi all,

I currently run some regressions on the hasti crossbar. I use a two masters and two slaves configuration. The following sequence seem to trigger incorrect behaviour: 
Master 1 issues three transfers to slave 0 (actually the number of transfers do not matter). Slave 0 will insert two wait states for any transfer. Master 0 that has higher priority (again this actually does not matter with respect to the issue) starts to issue three transfers to the same slave just one clock cycle after master 1, that will be stalled due to the wait states slave 0 insterts, has started its first tranfer. As soon as the slave asserts ready to acknowledge the first request of master 1 after two wait states also master 0 gets its ready signal being asserted which results in the first request of master 0 gets lost. Can onyone confirm this behaviour?

Stephan

**Comment by boehmerst** [comment]
master 1 issues three transfers to slave 0. Slave 0 inserts two wait states. Master 0 that has higher priority starts to issue three transfers to the same slave just one clock cycle after master 1, that is stalled due to the wait states slave 0 insterts. As soon as the slave gets to ready to acknoledge the first request of master 1 also master 0 gets ready resulting in this requests gets lost. Can onyone confirm this behaviour?

**Comment by boehmerst** [comment]
Sorry about accidentely closing the issue!

Thanks and regards
Stephan

**Comment by terpstra** [comment]
Hi. I just replaced the HastiXbar with a new implementation. Is your problem resolved?
