### ISSUE TITLE
Is junctions an obsolete repo?

### ISSUE THREAD

**Issue by edcote** [ucb-bar/junctions#22]
I see recent commits in:

https://github.com/ucb-bar/rocket-chip/tree/master/src/main/scala/junctions

that do not appear here, is this repo obsolete?

**Comment by terpstra** [comment]
The junctions repo is doubly obsolete. It's obsolete here, was updated a bit in rocket-chip, and is barely used there anymore... well on its way to being removed completely at some point.

**Comment by edcote** [comment]
What did rocket chip transition to?

**Comment by terpstra** [comment]
On Apr 11, 2017 8:03 PM, "Edmond Cote" <notifications@github.com> wrote:

> What did rocket chip transition to?
>

Uncore/ahb axi4 apb....

**Comment by edcote** [comment]
Thanks for the reply, Wesley!
